# Generated by Django 3.2.6 on 2022-05-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FactorApp', '0003_auto_20220527_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
